// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { Config, ConfigData } from "./tables/Config.sol";
import { Moderators } from "./tables/Moderators.sol";
import { Submissions, SubmissionsData } from "./tables/Submissions.sol";
import { Participants, ParticipantsData } from "./tables/Participants.sol";
import { Votes } from "./tables/Votes.sol";
