// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { ChestPrizeSystem } from "../../systems/ChestPrizeSystem.sol";
import { EntityId } from "@dust/world/src/types/EntityId.sol";
import { LeaderboardPosition } from "../common.sol";
import { revertWithBytes } from "@latticexyz/world/src/revertWithBytes.sol";
import { IWorldCall } from "@latticexyz/world/src/IWorldKernel.sol";
import { SystemCall } from "@latticexyz/world/src/SystemCall.sol";
import { WorldContextConsumerLib } from "@latticexyz/world/src/WorldContext.sol";
import { Systems } from "@latticexyz/world/src/codegen/tables/Systems.sol";
import { ResourceId } from "@latticexyz/store/src/ResourceId.sol";
import { StoreSwitch } from "@latticexyz/store/src/StoreSwitch.sol";

type ChestPrizeSystemType is bytes32;

// equivalent to WorldResourceIdLib.encode({ typeId: RESOURCE_SYSTEM, namespace: "DUST_HACK_1", name: "ChestPrizeSystem" }))
ChestPrizeSystemType constant chestPrizeSystem = ChestPrizeSystemType.wrap(
  0x7379445553545f4841434b5f3100000043686573745072697a6553797374656d
);

struct CallWrapper {
  ResourceId systemId;
  address from;
}

struct RootCallWrapper {
  ResourceId systemId;
  address from;
}

/**
 * @title ChestPrizeSystemLib
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This library is automatically generated from the corresponding system contract. Do not edit manually.
 */
library ChestPrizeSystemLib {
  error ChestPrizeSystemLib_CallingFromRootSystem();
  error NotModerator(address user);
  error InvalidPosition();

  function configureChest(ChestPrizeSystemType self, EntityId chest, LeaderboardPosition position) internal {
    return CallWrapper(self.toResourceId(), address(0)).configureChest(chest, position);
  }

  function removeChestConfig(ChestPrizeSystemType self, EntityId chest) internal {
    return CallWrapper(self.toResourceId(), address(0)).removeChestConfig(chest);
  }

  function configureChest(CallWrapper memory self, EntityId chest, LeaderboardPosition position) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ChestPrizeSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(
      _configureChest_EntityId_LeaderboardPosition.configureChest,
      (chest, position)
    );
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function removeChestConfig(CallWrapper memory self, EntityId chest) internal {
    // if the contract calling this function is a root system, it should use `callAsRoot`
    if (address(_world()) == address(this)) revert ChestPrizeSystemLib_CallingFromRootSystem();

    bytes memory systemCall = abi.encodeCall(_removeChestConfig_EntityId.removeChestConfig, (chest));
    self.from == address(0)
      ? _world().call(self.systemId, systemCall)
      : _world().callFrom(self.from, self.systemId, systemCall);
  }

  function configureChest(RootCallWrapper memory self, EntityId chest, LeaderboardPosition position) internal {
    bytes memory systemCall = abi.encodeCall(
      _configureChest_EntityId_LeaderboardPosition.configureChest,
      (chest, position)
    );
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function removeChestConfig(RootCallWrapper memory self, EntityId chest) internal {
    bytes memory systemCall = abi.encodeCall(_removeChestConfig_EntityId.removeChestConfig, (chest));
    SystemCall.callWithHooksOrRevert(self.from, self.systemId, systemCall, msg.value);
  }

  function callFrom(ChestPrizeSystemType self, address from) internal pure returns (CallWrapper memory) {
    return CallWrapper(self.toResourceId(), from);
  }

  function callAsRoot(ChestPrizeSystemType self) internal view returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), WorldContextConsumerLib._msgSender());
  }

  function callAsRootFrom(ChestPrizeSystemType self, address from) internal pure returns (RootCallWrapper memory) {
    return RootCallWrapper(self.toResourceId(), from);
  }

  function toResourceId(ChestPrizeSystemType self) internal pure returns (ResourceId) {
    return ResourceId.wrap(ChestPrizeSystemType.unwrap(self));
  }

  function fromResourceId(ResourceId resourceId) internal pure returns (ChestPrizeSystemType) {
    return ChestPrizeSystemType.wrap(resourceId.unwrap());
  }

  function getAddress(ChestPrizeSystemType self) internal view returns (address) {
    return Systems.getSystem(self.toResourceId());
  }

  function _world() private view returns (IWorldCall) {
    return IWorldCall(StoreSwitch.getStoreAddress());
  }
}

/**
 * System Function Interfaces
 *
 * We generate an interface for each system function, which is then used for encoding system calls.
 * This is necessary to handle function overloading correctly (which abi.encodeCall cannot).
 *
 * Each interface is uniquely named based on the function name and parameters to prevent collisions.
 */

interface _configureChest_EntityId_LeaderboardPosition {
  function configureChest(EntityId chest, LeaderboardPosition position) external;
}

interface _removeChestConfig_EntityId {
  function removeChestConfig(EntityId chest) external;
}

using ChestPrizeSystemLib for ChestPrizeSystemType global;
using ChestPrizeSystemLib for CallWrapper global;
using ChestPrizeSystemLib for RootCallWrapper global;
