// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

/**
 * @title IVotingSystem
 * @author MUD (https://mud.dev) by Lattice (https://lattice.xyz)
 * @dev This interface is automatically generated from the corresponding system contract. Do not edit manually.
 */
interface IVotingSystem {
  error AccessDenied(address user);
  error NotParticipant(address user);
  error AlreadySubmitted(address user);
  error NotFound(address creator);
  error NotInVotingPeriod(uint32 timestamp, uint32 votingStartTimestamp, uint32 votingEndTimestamp);
  error NoVotesLeft(address user, uint32 votesGiven, uint32 votesPerParticipant);
  error NoVotesToRevoke(address user, uint32 votesGiven);

  function dev_hack_1__setModerator(address user, bool isModerator) external;

  function dev_hack_1__setConfig(
    uint32 votingStartTimestamp,
    uint32 votingEndTimestamp,
    uint32 votesPerParticipant
  ) external;

  function dev_hack_1__registerParticipant(address user) external;

  function dev_hack_1__createSubmission(
    string memory name,
    string memory githubUrl,
    string memory demoVideoUrl
  ) external;

  function dev_hack_1__updateName(string memory name) external;

  function dev_hack_1__updateGithubUrl(string memory githubUrl) external;

  function dev_hack_1__updateDemoVideoUrl(string memory demoVideoUrl) external;

  function dev_hack_1__vote(address creator) external;

  function dev_hack_1__revokeVote(address creator) external;
}
